export function capitalize(string) {
    return string[0].toLocaleUpperCase() + string.slice(1);
}

let countryFlags = {
    'AFGHANISTAN': require('../assets/flags/af.png'),
    'ALBANIA': require('../assets/flags/al.png'),
    'ALGERIA': require('../assets/flags/dz.png'),
    'AMERICAN SAMOA': require('../assets/flags/as.png'),
    'ANDORRA': require('../assets/flags/ad.png'),
    'ANGOLA': require('../assets/flags/ao.png'),
    'ANGUILLA': require('../assets/flags/ai.png'),
    'ANTARCTICA': require('../assets/flags/aq.png'),
    'ANTIGUA AND BARBUDA': require('../assets/flags/ag.png'),
    'ARGENTINA': require('../assets/flags/ar.png'),
    'ARMENIA': require('../assets/flags/am.png'),
    'ARUBA': require('../assets/flags/aw.png'),
    'AUSTRALIA': require('../assets/flags/au.png'),
    'AUSTRIA': require('../assets/flags/at.png'),
    'AZERBAIJAN': require('../assets/flags/az.png'),
    'BAHAMAS': require('../assets/flags/bs.png'),
    'BAHRAIN': require('../assets/flags/bh.png'),
    'BANGLADESH': require('../assets/flags/bd.png'),
    'BARBADOS': require('../assets/flags/bb.png'),
    'BELARUS': require('../assets/flags/by.png'),
    'BELGIUM': require('../assets/flags/be.png'),
    'BELIZE': require('../assets/flags/bz.png'),
    'BENIN': require('../assets/flags/bj.png'),
    'BERMUDA': require('../assets/flags/bm.png'),
    'BHUTAN': require('../assets/flags/bt.png'),
    'BOLIVIA': require('../assets/flags/bo.png'),
    'BOSNIA AND HERZEGOVINA': require('../assets/flags/ba.png'),
    'BOTSWANA': require('../assets/flags/bw.png'),
    'BRAZIL': require('../assets/flags/br.png'),
    'BRUNEI DARUSSALAM': require('../assets/flags/bn.png'),
    'BULGARIA': require('../assets/flags/bg.png'),
    'BURKINA FASO': require('../assets/flags/bf.png'),
    'BURUNDI': require('../assets/flags/bi.png'),
    'CAMBODIA': require('../assets/flags/kh.png'),
    'CAMEROON': require('../assets/flags/cm.png'),
    'CANADA': require('../assets/flags/ca.png'),
    'CAPE VERDE': require('../assets/flags/cv.png'),
    'CAYMAN ISLANDS': require('../assets/flags/ky.png'),
    'CENTRAL AFRICAN REPUBLIC': require('../assets/flags/cf.png'),
    'CHAD': require('../assets/flags/td.png'),
    'CHILE': require('../assets/flags/cl.png'),
    'CHINA': require('../assets/flags/cn.png'),
    'COLOMBIA': require('../assets/flags/co.png'),
    'COMOROS': require('../assets/flags/km.png'),
    'CONGO': require('../assets/flags/cg.png'),
    'CONGO, DEMOCRATIC REPUBLIC': require('../assets/flags/cd.png'),
    'COOK ISLANDS': require('../assets/flags/ck.png'),
    'COSTA RICA': require('../assets/flags/cr.png'),
    'COTE D\'IVOIRE': require('../assets/flags/ci.png'),
    'CROATIA': require('../assets/flags/hr.png'),
    'CUBA': require('../assets/flags/cu.png'),
    'CYPRUS': require('../assets/flags/cy.png'),
    'CZECH REPUBLIC': require('../assets/flags/cz.png'),
    'DENMARK': require('../assets/flags/dk.png'),
    'DJIBOUTI': require('../assets/flags/dj.png'),
    'DOMINICA': require('../assets/flags/dm.png'),
    'DOMINICAN REPUBLIC': require('../assets/flags/do.png'),
    'ECUADOR': require('../assets/flags/ec.png'),
    'EGYPT': require('../assets/flags/eg.png'),
    'EL SALVADOR': require('../assets/flags/sv.png'),
    'EQUATORIAL GUINEA': require('../assets/flags/gq.png'),
    'ESTONIA': require('../assets/flags/ee.png'),
    'ETHIOPIA': require('../assets/flags/et.png'),
    'FAROE ISLANDS': require('../assets/flags/fo.png'),
    'FIJI': require('../assets/flags/fj.png'),
    'FINLAND': require('../assets/flags/fi.png'),
    'FRANCE': require('../assets/flags/fr.png'),
    'FRENCH POLYNESIA': require('../assets/flags/pf.png'),
    'GABON': require('../assets/flags/ga.png'),
    'GAMBIA': require('../assets/flags/gm.png'),
    'GEORGIA': require('../assets/flags/ge.png'),
    'GERMANY': require('../assets/flags/de.png'),
    'GHANA': require('../assets/flags/gh.png'),
    'GIBRALTAR': require('../assets/flags/gi.png'),
    'GREECE': require('../assets/flags/gr.png'),
    'GREENLAND': require('../assets/flags/gl.png'),
    'GRENADA': require('../assets/flags/gd.png'),
    'GUADELOUPE': require('../assets/flags/gp.png'),
    'GUAM': require('../assets/flags/gu.png'),
    'GUATEMALA': require('../assets/flags/gt.png'),
    'GUERNSEY': require('../assets/flags/gg.png'),
    'GUINEA': require('../assets/flags/gn.png'),
    'GUINEA-BISSAU': require('../assets/flags/gw.png'),
    'GUYANA': require('../assets/flags/gy.png'),
    'HAITI': require('../assets/flags/ht.png'),
    'HOLY SEE (VATICAN CITY STATE)': require('../assets/flags/va.png'),
    'HONDURAS': require('../assets/flags/hn.png'),
    'HONG KONG': require('../assets/flags/hk.png'),
    'HUNGARY': require('../assets/flags/hu.png'),
    'ICELAND': require('../assets/flags/is.png'),
    'INDIA': require('../assets/flags/in.png'),
    'INDONESIA': require('../assets/flags/id.png'),
    'IRAN, ISLAMIC REPUBLIC OF': require('../assets/flags/ir.png'),
    'IRAQ': require('../assets/flags/iq.png'),
    'IRELAND': require('../assets/flags/ie.png'),
    'ISLE OF MAN': require('../assets/flags/im.png'),
    'ISRAEL': require('../assets/flags/il.png'),
    'ITALY': require('../assets/flags/it.png'),
    'JAMAICA': require('../assets/flags/jm.png'),
    'JAPAN': require('../assets/flags/jp.png'),
    'JERSEY': require('../assets/flags/je.png'),
    'JORDAN': require('../assets/flags/jo.png'),
    'KAZAKHSTAN': require('../assets/flags/kz.png'),
    'KENYA': require('../assets/flags/ke.png'),
    'KIRIBATI': require('../assets/flags/ki.png'),
    'KOREA': require('../assets/flags/kr.png'),
    'KUWAIT': require('../assets/flags/kw.png'),
    'KYRGYZSTAN': require('../assets/flags/kg.png'),
    'LAO PEOPLE\'S DEMOCRATIC REPUBLIC': require('../assets/flags/la.png'),
    'LATVIA': require('../assets/flags/lv.png'),
    'LEBANON': require('../assets/flags/lb.png'),
    'LESOTHO': require('../assets/flags/ls.png'),
    'LIBERIA': require('../assets/flags/lr.png'),
    'LIBYAN ARAB JAMAHIRIYA': require('../assets/flags/ly.png'),
    'LIECHTENSTEIN': require('../assets/flags/li.png'),
    'LITHUANIA': require('../assets/flags/lt.png'),
    'LUXEMBOURG': require('../assets/flags/lu.png'),
    'MACAO': require('../assets/flags/mo.png'),
    'MACEDONIA': require('../assets/flags/mk.png'),
    'MADAGASCAR': require('../assets/flags/mg.png'),
    'MALAWI': require('../assets/flags/mw.png'),
    'MALAYSIA': require('../assets/flags/my.png'),
    'MALDIVES': require('../assets/flags/mv.png'),
    'MALI': require('../assets/flags/ml.png'),
    'MALTA': require('../assets/flags/mt.png'),
    'MARSHALL ISLANDS': require('../assets/flags/mh.png'),
    'MARTINIQUE': require('../assets/flags/mq.png'),
    'MAURITANIA': require('../assets/flags/mr.png'),
    'MAURITIUS': require('../assets/flags/mu.png'),
    'MEXICO': require('../assets/flags/mx.png'),
    'MICRONESIA, FEDERATED STATES OF': require('../assets/flags/fm.png'),
    'MOLDOVA': require('../assets/flags/md.png'),
    'MONACO': require('../assets/flags/mc.png'),
    'MONGOLIA': require('../assets/flags/mn.png'),
    'MONTENEGRO': require('../assets/flags/me.png'),
    'MONTSERRAT': require('../assets/flags/ms.png'),
    'MOROCCO': require('../assets/flags/ma.png'),
    'MOZAMBIQUE': require('../assets/flags/mz.png'),
    'MYANMAR': require('../assets/flags/mm.png'),
    'NAMIBIA': require('../assets/flags/na.png'),
    'NAURU': require('../assets/flags/nr.png'),
    'NEPAL': require('../assets/flags/np.png'),
    'NETHERLANDS': require('../assets/flags/nl.png'),
    'NETHERLANDS ANTILLES': require('../assets/flags/an.png'),
    'NEW CALEDONIA': require('../assets/flags/nc.png'),
    'NEW ZEALAND': require('../assets/flags/nz.png'),
    'NICARAGUA': require('../assets/flags/ni.png'),
    'NIGER': require('../assets/flags/ne.png'),
    'NIGERIA': require('../assets/flags/ng.png'),
    'NORWAY': require('../assets/flags/no.png'),
    'OMAN': require('../assets/flags/om.png'),
    'PAKISTAN': require('../assets/flags/pk.png'),
    'PALAU': require('../assets/flags/pw.png'),
    'PALESTINIAN TERRITORY, OCCUPIED': require('../assets/flags/ps.png'),
    'PANAMA': require('../assets/flags/pa.png'),
    'PAPUA NEW GUINEA': require('../assets/flags/pg.png'),
    'PARAGUAY': require('../assets/flags/py.png'),
    'PERU': require('../assets/flags/pe.png'),
    'PHILIPPINES': require('../assets/flags/ph.png'),
    'POLAND': require('../assets/flags/pl.png'),
    'PORTUGAL': require('../assets/flags/pt.png'),
    'PUERTO RICO': require('../assets/flags/pr.png'),
    'QATAR': require('../assets/flags/qa.png'),
    'REUNION': require('../assets/flags/re.png'),
    'ROMANIA': require('../assets/flags/ro.png'),
    'RUSSIAN FEDERATION': require('../assets/flags/ru.png'),
    'RWANDA': require('../assets/flags/rw.png'),
    'SAINT KITTS AND NEVIS': require('../assets/flags/kn.png'),
    'SAINT LUCIA': require('../assets/flags/lc.png'),
    'SAINT VINCENT AND GRENADINES': require('../assets/flags/vc.png'),
    'SAMOA': require('../assets/flags/ws.png'),
    'SAN MARINO': require('../assets/flags/sm.png'),
    'SAO TOME AND PRINCIPE': require('../assets/flags/st.png'),
    'SAUDI ARABIA': require('../assets/flags/sa.png'),
    'SENEGAL': require('../assets/flags/sn.png'),
    'SERBIA': require('../assets/flags/rs.png'),
    'SEYCHELLES': require('../assets/flags/sc.png'),
    'SIERRA LEONE': require('../assets/flags/sl.png'),
    'SINGAPORE': require('../assets/flags/sg.png'),
    'SLOVAKIA': require('../assets/flags/sk.png'),
    'SLOVENIA': require('../assets/flags/si.png'),
    'SOLOMON ISLANDS': require('../assets/flags/sb.png'),
    'SOMALIA': require('../assets/flags/so.png'),
    'SOUTH AFRICA': require('../assets/flags/za.png'),
    'SPAIN': require('../assets/flags/es.png'),
    'SRI LANKA': require('../assets/flags/lk.png'),
    'SUDAN': require('../assets/flags/sd.png'),
    'SURINAME': require('../assets/flags/sr.png'),
    'SWAZILAND': require('../assets/flags/sz.png'),
    'SWEDEN': require('../assets/flags/se.png'),
    'SWITZERLAND': require('../assets/flags/ch.png'),
    'SYRIAN ARAB REPUBLIC': require('../assets/flags/sy.png'),
    'TAIWAN': require('../assets/flags/tw.png'),
    'TAJIKISTAN': require('../assets/flags/tj.png'),
    'TANZANIA': require('../assets/flags/tz.png'),
    'THAILAND': require('../assets/flags/th.png'),
    'TIMOR-LESTE': require('../assets/flags/tl.png'),
    'TOGO': require('../assets/flags/tg.png'),
    'TONGA': require('../assets/flags/to.png'),
    'TRINIDAD AND TOBAGO': require('../assets/flags/tt.png'),
    'TUNISIA': require('../assets/flags/tn.png'),
    'TURKEY': require('../assets/flags/tr.png'),
    'TURKMENISTAN': require('../assets/flags/tm.png'),
    'TURKS AND CAICOS ISLANDS': require('../assets/flags/tc.png'),
    'TUVALU': require('../assets/flags/tv.png'),
    'UGANDA': require('../assets/flags/ug.png'),
    'UKRAINE': require('../assets/flags/ua.png'),
    'UNITED ARAB EMIRATES': require('../assets/flags/ae.png'),
    'UNITED KINGDOM': require('../assets/flags/gb.png'),
    'UNITED STATES': require('../assets/flags/us.png'),
    'URUGUAY': require('../assets/flags/uy.png'),
    'UZBEKISTAN': require('../assets/flags/uz.png'),
    'VANUATU': require('../assets/flags/vu.png'),
    'VENEZUELA': require('../assets/flags/ve.png'),
    'VIET NAM': require('../assets/flags/vn.png'),
    'VIRGIN ISLANDS, BRITISH': require('../assets/flags/vg.png'),
    'VIRGIN ISLANDS, U.S.': require('../assets/flags/vi.png'),
    'WESTERN SAHARA': require('../assets/flags/eh.png'),
    'YEMEN': require('../assets/flags/ye.png'),
    'ZAMBIA': require('../assets/flags/zm.png'),
    'ZIMBABWE': require('../assets/flags/zw.png')
};

export function getCountryFlag(countryName) {
    let upperCaseCountryName = countryName.toUpperCase();
    if (countryFlags.hasOwnProperty(upperCaseCountryName)) {
        return countryFlags[upperCaseCountryName];
    }
}
